### PR TITLE
Wildcard for 'clibs/strdup'

### PR DESCRIPTION
**Pull request by jwerle**

### CODE REVIEW

**Comment by stephenmathieson** [comment]
This seems fine to me, but why is it necessary?

**Comment by jwerle** [comment]
For the same reason as `stephenmathieson/occurrences.c`, I guess? :man_shrugging: We don't support semver and it I think `strdup` in `str-replace` should be the latest and greatest

**Comment by stephenmathieson** [comment]
Haha ok, works for me.

**Comment by stephenmathieson** [comment]
Just added you as a collaborator on this repo. Feel free to make any other changes you need 👍

**Comment by jwerle** [comment]
thanks !!

**Pull request merged**
